### PR TITLE
1.x 2.x issue 140

### PR DESCRIPTION
**Pull request by argiepiano**

### CODE REVIEW

**Comment by laryn** [comment]
@argiepiano 

Should this:
> if (strpos(!$item || $item['path'], 'node/add/') !== 0) {

be this?

> if (!$item || strpos($item['path'], 'node/add/') !== 0) {

**Comment by argiepiano** [comment]
Oops!!! Yes. Thanks for catching that. I'll fix soon

**Comment by argiepiano** [comment]
Fixed!

**Comment by laryn** [comment]
LGTM

**Pull request merged**
